import { FlexAlignType, FlexStyle, TextStyle } from 'react-native';

export const theme = {
  components: {
    display: {
      flex: 'flex' as FlexStyle['display'],
      none: 'none' as FlexStyle['display'],
      block: 'block' as FlexStyle['display'],
    },
    flexDirection: {
      row: 'row' as FlexStyle['flexDirection'],
      column: 'column' as FlexStyle['flexDirection'],
      rowReverse: 'row-reverse' as FlexStyle['flexDirection'],
      columnReverse: 'column-reverse' as FlexStyle['flexDirection'],
    },
    alignItems: {
      center: 'center' as FlexAlignType,
      flexStart: 'flex-start' as FlexAlignType,
      flexEnd: 'flex-end' as FlexAlignType,
      stretch: 'stretch' as FlexAlignType,
      baseline: 'baseline' as FlexAlignType,
    },
    justifyContent: {
      center: 'center' as FlexStyle['justifyContent'],
      flexStart: 'flex-start' as FlexStyle['justifyContent'],
      flexEnd: 'flex-end' as FlexStyle['justifyContent'],
      spaceBetween: 'space-between' as FlexStyle['justifyContent'],
      spaceAround: 'space-around' as FlexStyle['justifyContent'],
      spaceEvenly: 'space-evenly' as FlexStyle['justifyContent'],
    },
    position: {
      absolute: 'absolute' as FlexStyle['position'],
      relative: 'relative' as FlexStyle['position'],
    },
    colorScheme: {
      primary: {
        greenBunny: {
          10: '#e6f6f4',
          20: '#d9f2ef',
          30: '#b0e4dd',
          40: '#00a991',
          50: '#009883',
          60: '#008774',
          70: '#007f6d',
          80: '#006557',
          90: '#004c41',
          100: '#003b33',
        },
        darkBunny: {
          10: '#e6e6e6',
          20: '#cccccc',
          30: '#b3b3b3',
          40: '#999999',
          50: '#808080',
          60: '#676767',
          70: '#4d4d4d',
          80: '#343434',
          90: '#1a1a1a',
          100: '#010101',
        },
        canvasBunny: '#F7F7F7',
        whiteBunny: '#FFFFFF',
        brightBunny: '#F5F9FC',
      },
      common: {
        Info: '#0AC9C9',
        Success: '#8EEA77',
        Warning: '#FFD012',
        Error: '#EA6950',
        SuccessDark: '#30B20F',
      },
    },
    fonts: {
      light: 'WorkSans_300Light',
      regular: 'WorkSans_400Regular',
      medium: 'WorkSans_500Medium',
      semiBold: 'WorkSans_600SemiBold',
      bold: 'WorkSans_700Bold',
      extraBoldItalic: 'WorkSans_800ExtraBold_Italic',
      WorkSans_100Thin: 'WorkSans_100Thin',
      WorkSans_200ExtraLight: 'WorkSans_200ExtraLight',
      WorkSans_300Light: 'WorkSans_300Light',
      WorkSans_400Regular: 'WorkSans_400Regular',
      WorkSans_500Medium: 'WorkSans_500Medium',
      WorkSans_600SemiBold: 'WorkSans_600SemiBold',
      WorkSans_700Bold: 'WorkSans_700Bold',
      WorkSans_800ExtraBold: 'WorkSans_800ExtraBold',
      WorkSans_900Black: 'WorkSans_900Black',
      WorkSans_100Thin_Italic: 'WorkSans_100Thin_Italic',
      WorkSans_200ExtraLight_Italic: 'WorkSans_200ExtraLight_Italic',
      WorkSans_300Light_Italic: 'WorkSans_300Light_Italic',
      WorkSans_400Regular_Italic: 'WorkSans_400Regular_Italic',
      WorkSans_500Medium_Italic: 'WorkSans_500Medium_Italic',
      WorkSans_600SemiBold_Italic: 'WorkSans_600SemiBold_Italic',
      WorkSans_700Bold_Italic: 'WorkSans_700Bold_Italic',
      WorkSans_800ExtraBold_Italic: 'WorkSans_800ExtraBold_Italic',
      WorkSans_900Black_Italic: 'WorkSans_900Black_Italic',
    },
    fontSizes: {
      heading: {
        xl: 64,
        h1: 40,
        h2: 36,
        h3: 32,
        h4: 24,
        h5: 20,
        h6: 18,
        h7: 16,
        h8: 14,
      },
      body: {
        b1: 18,
        b2: 16,
        b3: 14,
        b4: 12,
      },
    },
    spacing: {
      0: 0,
      0.5: 2,
      1: 4,
      2: 8,
      3: 12,
      4: 16,
      5: 24,
      6: 32,
      7: 40,
      8: 48,
      9: 56,
      10: 64,
      11: 80,
      12: 120,
      13: 160,
    },
    borderRadius: {
      0: 0,
      1: 4,
      2: 8,
      3: 12,
      4: 16,
      5: 24,
      6: 32,
      7: 40,
      8: 48,
      9: 56,
      10: 64,
      11: 80,
      12: 100,
    },
  },
};
